# Data Loading - Superstore

This notebook loads the exported CSV files generated from the SQL Superstore project.  
The goal of this step is to verify data structure and completeness before any further transformations or analysis.

#### The following datasets are loaded:
- fact_sales.csv
- dim_customer.csv
- dim_product.csv

#### This notebook focuses on:
- Inspecting columns and structure
- Checking for missing values
- Checking the uniqueness of key columns

In [1]:
import pandas as pd

In [2]:
customers = pd.read_csv("../data/dim_customer.csv")
products = pd.read_csv("../data/dim_product.csv")
sales = pd.read_csv("../data/fact_sales.csv")

In [3]:
customers.shape

(793, 3)

In [4]:
products.shape

(1862, 4)

In [5]:
sales.shape

(9994, 16)

### Data Quality Check

Below section of this notebook:
- reviews the columns and first rows of each table
- counts missing values in all columns
- checks for duplicates in each key column

This is to ensure that the uploaded data is reliable and appropriate for further transformation and analysis.

In [6]:
customers.head(2)

  customer_id  customer_name    segment
0    JC-15775   John Castell   Consumer
1    EB-13840  Ellis Ballard  Corporate

In [7]:
products.head(2)

,product_id,category,sub_category,product_name
0,FUR-BO-10000112,Furniture,Bookcases,"Bush Birmingham Collection Bookcase, Dark Cherry"
1,FUR-BO-10000330,Furniture,Bookcases,"Sauder Camden County Barrister Bookcase, Plank..."

In [8]:
sales.head(2)

,row_id,order_id,order_date_day,ship_date_day,ship_mode,customer_id,country,state,city,postal_code,region,product_id,sales,quantity,discount,profit
0,9648,CA-2014-150518,2014-11-19,2014-11-24,Standard Class,MW-18220,United States,Minnesota,Coon Rapids,55433,Central,OFF-ST-10000877,221.160,4,0.0,57.5016
1,2382,CA-2016-118052,2016-05-06,2016-05-10,Standard Class,BE-11455,United States,Ohio,Lorain,44052,East,FUR-FU-10004848,54.712,7,0.2,11.6263

In [9]:
customers.isnull().sum()

customer_id      0
customer_name    0
segment          0
dtype: int64

In [10]:
products.isnull().sum()

product_id      0
category        0
sub_category    0
product_name    0
dtype: int64

In [11]:
sales.isnull().sum()

row_id            0
order_id          0
order_date_day    0
ship_date_day     0
ship_mode         0
customer_id       0
country           0
state             0
city              0
postal_code       0
region            0
product_id        0
sales             0
quantity          0
discount          0
profit            0
dtype: int64

In [12]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [13]:
products["product_id"].duplicated().sum()

np.int64(0)

In [14]:
sales["row_id"].duplicated().sum()

np.int64(0)